#!/bin/sh

set -e

case "$1" in
    install|upgrade)
      if ! getent group gumo >/dev/null; then
        addgroup --system gumo
      fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0