#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
      if getent group gumo >/dev/null; then
        delgroup --system gumo
      fi
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0