#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
      delgroup --system gumo
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0