name: Create the Gumo DEB

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Copy necessary files
        run: |
          mkdir -p PKG_SOURCE/usr/local/bin
          mkdir -p PKG_SOURCE/etc/gumo
          cp -Rf ./DEBIAN PKG_SOURCE/
          cp -Rf ./gumo PKG_SOURCE/usr/local/bin/
          cp -Rf ./gumo.properties.template PKG_SOURCE/etc/gumo/gumo.properties
          cp -Rf ./gumo.messages PKG_SOURCE/etc/gumo/

      - name: Create Deb package
        run: |
          dpkg-deb --build PKG_SOURCE gumo_${{github.ref_name}}_${{ matrix.platform }}.deb

      - name: Release the Deb package
        uses: softprops/action-gh-release@v1
        with:
          files: gumo_${{github.ref_name}}_${{ matrix.platform }}.deb