name: Create the Gumo DEB

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Copy necessary files
        run: |
          mkdir PKG_SOURCE
          cp -Rf ./gumo ./debian PKG_SOURCE
          dpkg-deb --build PKG_SOURCE gumo.deb

      - name: Release the Deb package
        uses: softprops/action-gh-release@v1
        with:
          files: gumo.deb